/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttendanceTable: typeof import('./src/components/AttendanceTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scanner: typeof import('./src/components/Scanner.vue')['default']
    StatsCards: typeof import('./src/components/StatsCards.vue')['default']
    StatusBar: typeof import('./src/components/StatusBar.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    Users: typeof import('./src/components/Users.vue')['default']
  }
}
